### ISSUE TITLE
minor bugs

### ISSUE THREAD

**Issue by babeheim** [jabunce/bunce-mcelreath-HN-2016-matsigenka-norms#1]
In `Interviews_IRT_9jan17.R' line 153 is

```r
props1 <- cbind(props, quest_names)
```
but it should be 

```r
props1 <- cbind(props1, quest_names)
```
Same issue in `Fig2_9jan17.R`

There's also a `NULL` character on line 4392 of `Interviews_IRT_9jan17.R' that is causing downstream issues on my computer. The corrected line should be 

```r
  round(mean(post11$bmat), digs),  #
```

**Comment by jabunce** [comment]
Thanks Bret! Should be fixed now.

For others reading: These changes don't affect content of the analysis.
